// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Medicine.Migrations
{
    [DbContext(typeof(MedicalDbContext))]
    [Migration("20260425040020_InitialMedicalSchema")]
    partial class InitialMedicalSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medicine.Models.Contraindication", b =>
                {
                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<string>("WarningNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrugId", "DiseaseId");

                    b.HasIndex("DiseaseId");

                    b.ToTable("Contraindications");
                });

            modelBuilder.Entity("Medicine.Models.Disease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icd10Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diseases");
                });

            modelBuilder.Entity("Medicine.Models.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("Medicine.Models.DrugInteraction", b =>
                {
                    b.Property<int>("SourceDrugId")
                        .HasColumnType("int");

                    b.Property<int>("TargetDrugId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SourceDrugId", "TargetDrugId");

                    b.HasIndex("TargetDrugId");

                    b.ToTable("DrugInteractions");
                });

            modelBuilder.Entity("Medicine.Models.Indication", b =>
                {
                    b.Property<int>("DrugId")
                        .HasColumnType("int");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<string>("DosageInstruction")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrugId", "DiseaseId");

                    b.HasIndex("DiseaseId");

                    b.ToTable("Indications");
                });

            modelBuilder.Entity("Medicine.Models.Contraindication", b =>
                {
                    b.HasOne("Medicine.Models.Disease", "Disease")
                        .WithMany("Contraindications")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medicine.Models.Drug", "Drug")
                        .WithMany("Contraindications")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("Medicine.Models.DrugInteraction", b =>
                {
                    b.HasOne("Medicine.Models.Drug", "SourceDrug")
                        .WithMany("InteractionsAsSource")
                        .HasForeignKey("SourceDrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Medicine.Models.Drug", "TargetDrug")
                        .WithMany("InteractionsAsTarget")
                        .HasForeignKey("TargetDrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceDrug");

                    b.Navigation("TargetDrug");
                });

            modelBuilder.Entity("Medicine.Models.Indication", b =>
                {
                    b.HasOne("Medicine.Models.Disease", "Disease")
                        .WithMany("Indications")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Medicine.Models.Drug", "Drug")
                        .WithMany("Indications")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Drug");
                });

            modelBuilder.Entity("Medicine.Models.Disease", b =>
                {
                    b.Navigation("Contraindications");

                    b.Navigation("Indications");
                });

            modelBuilder.Entity("Medicine.Models.Drug", b =>
                {
                    b.Navigation("Contraindications");

                    b.Navigation("Indications");

                    b.Navigation("InteractionsAsSource");

                    b.Navigation("InteractionsAsTarget");
                });
#pragma warning restore 612, 618
        }
    }
}
